"""
Django settings for trakberry project.

Generated by 'django-admin startproject' using Django 1.8.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=-#i@xqkfo!o4)v1786$u2(-0&9j*o6hufkl(m9vg2!yci%xkx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

MEDIA_URL = '/media/'

TEMPLATE_DIRS = (
    '/templates/',
)

# Application definition

INSTALLED_APPS = (
    'django_admin_bootstrapped',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'polls',
    'trakberry',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'trakberry.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trakberry.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#    }
#}  

# UnComment the below Database Setting to use on the PMDSDATA Server
# DATABASES = {
#          'default': {
#              'ENGINE': 'django.db.backends.mysql', 
#              'NAME': 'prodrptdb',                      
#              'USER': 'stuser',                      
#              'HOST': '10.4.1.224', 
#              'PASSWORD':'stp383', 
#          }
#           }

# DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.mysql',
# 	        'NAME': 'prodrptdb',
# 		    'USER': 'root',
# 		    'PASSWORD':'password',
# 		    'HOST': '127.0.0.1',
# 		    'PORT': '',
#          }
#       }

# Use the below Database Setting to use on the local Server
DATABASES = {

       'default': {
           'ENGINE': 'django.db.backends.mysql',
	        'NAME': 'prodrptdb',
		    'USER': 'root',
		    'PASSWORD':'benny6868',
		    'HOST': '127.0.0.1',
		    'PORT': '',
        }
     }


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'US/Eastern'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATIC_URL = '/static/'

# The below section will try and import the local database first but if it can't find it will use server
# try:
#     from local_settings import *
# except ImportError:
#     pass






